### ISSUE TITLE
github pages doesn't track master branch on this repo

### ISSUE THREAD

**Issue by theofficialgman** [Pi-Apps-Coders/docs#4]
https://github.com/Pi-Apps-Coders/docs/deployments/activity_log?environment=github-pages
last time it was deployed was 10 days ago since it tracks the gh-pages branch
so the apps list on the gh-pages branch gets out of date even though the master branch stays up to date.

I assume this was intentional?

**Comment by ryanfortner** [comment]
No, that isn't intentional, but condensing both the appslist and publish jobs into [one GitHub Action](https://github.com/Pi-Apps-Coders/docs/blob/master/.github/workflows/publish-docs.yml) seems to fix the issue.
